apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-pv-claim
spec:
  storageClassName: manual
  volumeName: chat-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
